### PR TITLE
Move 'conference' below in INSTALLED_APPS

### PR DESCRIPTION
**Pull request by alexsavio**

### CODE REVIEW

**Comment by fpliger** [comment]
Why this PR? Aren't you already doing it in #8 ?

**Comment by alexsavio** [comment]
I closed it. Decided to do things separately. There were too many mixed stuff in #8, no?

**Comment by fpliger** [comment]
I don't think so... (reasonable size, even if smaller PRs a better to review it was very straightfoward) IMHO was also almost good enough to be merged but feel free to do as you prefer!  ;-)

**Comment by alexsavio** [comment]
Ok. I'm really getting confused on how Github is managing this. I'll stick back to #8.

**Pull request closed without merging**
