### PR TITLE
[WIP] Python 3 support

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by matrixise** [comment]
just one question, how did you proceed?

Thank you

**Comment by michael-k** [comment]
I did not yet proceed.  I switched to something else.

**Comment by matrixise** [comment]
but for the convertion from 2 to 3? with 2to3? or a big ack/sed ?

**Comment by michael-k** [comment]
No, I'm approaching one problem at the time by hand.  This way I get smaller commits and I can think about what I'm doing.

**Comment by sparkiegeek** [comment]
I've noticed in this branch that you've removed `django-pingback` which is also a blocker for upgrading Django versions, maybe we can extract that into a separate PR?

**Update**: I've done this in #767

**Pull request closed without merging**
