### PR TITLE
WIP Design/update carousel for 2018

### PR DESCRIPTION
**Pull request by artcz**
TODO:
* make sure carousel css works correctly with responsive design
* possibly replace pictures with different resolutions

DONE:
* introduced new file where we can overwrite css specifically for ep2018
* basic img[src] with z-index: -1 carousel implementation in jquery

TESTED BUT REMOVED:
* background-image based carosuel – there's no good way to animate transition of background-image

### CODE REVIEW

**Comment by artcz** [comment]
Maybe instead of implementing carousel (that switches pictures in js every couple of seconds) we could just pick a random background on every refresh? (so the background doesn't change when you're on the page, but it changes when you go to another page, or hit refresh)

Motivation: it still requires some debugging, and making sure it scales correctly on mobile; vs just picking random picture would work out of the box with current CSS.

**Comment by artcz** [comment]
We should probably replace it with simply choosing a random backgorund on every refresh without the carousel animation (makes it much easier to work correctly on mobile as well)

**Comment by malemburg** [comment]
The random background would work as well. Can we get this done today, to finalize this part ? The PR no longer applies cleanly.

I'd like to get the CSS colors fixed for EP2018 as well, based on the green color in the logo.

**Comment by artcz** [comment]
Closing because replaced by new PR w/o the carousel part.

**Pull request closed without merging**
