### PR TITLE
[WIP] Save given and family name separately on CFPs

### LINKED ISSUE #997: Request first and last name separately when submitting talk proposals during cfp
Related to https://github.com/EuroPython/epcon/issues/988

### PR DESCRIPTION
**Pull request by aleszoulek**
Fixes #997

### CODE REVIEW

**Comment by aleszoulek** [comment]
There are several TODOs:
- improve UI wording (see attached image)
- eventually, we should datamigarate our data, so we don't have to do checks like `first_name.endswith(last_name)` [may be out of scope for this one?]


Screenshot 2019-07-13 at 12 44 33

**Comment by umgelurgel** [comment]
The test you're mentioning is from `AssopyUser.name`, right? I'd leave removing that outside of the scope, I'd need to confirm production data has been fixed.

**Comment by umgelurgel** [comment]
Thanks for you work on hits, @aleszoulek !

**Comment by umgelurgel** [comment]
The changes from this MR have been moved to https://github.com/EuroPython/epcon/pull/1147 and additional tests have been added. Thanks for your work on this, @aleszoulek !

**Pull request closed without merging**
