### PR TITLE
Removed Badge Code

### LINKED ISSUE #796: Remove old badge generation code
Currently we generate badges using separate piece of software, we just get data from epcon to populate it. There are some old functions related to badge generation, we can safely remove them.

### PR DESCRIPTION
**Pull request by hmajid2301**
Removed all code related to rendering badges

Fixes #796

### CODE REVIEW

**Comment by artcz** [comment]
Hi Haseeb

Could you rebase this branch on the latest dev/ep2019? Github reports some merge conflicts above ↑

Thanks

**Comment by hmajid2301** [comment]
Done :)

**Review by artcz — APPROVED** [review]
LGTM
FYI for other people – badges code leaves somewhere else these days. :)

**Comment by artcz** [comment]
Merged. 
Thanks. :)

**Pull request merged**
