### PR TITLE
[WIP] Translate the comments to English

### PR DESCRIPTION
**Pull request by matrixise**
I work on the English translation

### CODE REVIEW

**Comment by alexsavio** [comment]
LGTM. I would merge it as it is.

**Comment by malemburg** [comment]
It looks mostly fine, but in some cases you have removed/not translated some extra information in the comments/doc strings which are helpful to understand what the methods/functions do, e.g. https://github.com/EuroPython/epcon/pull/390/commits/21e6342021665ecfe1f534ed4ba5650bda87c8e9#diff-69308c7e9087b815c07b9ec6f5609f43L190, https://github.com/EuroPython/epcon/pull/390/commits/21e6342021665ecfe1f534ed4ba5650bda87c8e9#diff-69308c7e9087b815c07b9ec6f5609f43L548,   Could you complete those parts so that we don't lose useful information ?

**Comment by alexsavio** [comment]
@matrixise could you please add the comment so we can get your PR merged? Thank you.

**Comment by alexsavio** [comment]
Nice work. LGTM :+1:

**Pull request merged**
