### PR TITLE
added STRIPE_CURRENCY

### PR DESCRIPTION
**Pull request by barrachri**
added STRIPE_CURRENCY

### CODE REVIEW

**Comment by oiertwo** [comment]
I am testing this too, but my idea is to set all the STRIPE variables in the same way.

using this:
STRIPE_CURRENCY = os.environ.get("STRIPE_CURRENCY")

and set STRIPE_CURRENCY in the environment in some script outsite.

**Comment by barrachri** [comment]
I think is useless...

1) This var is used for a template tag
2) Actually the currency of the payments is hardcoded inside stripe/views.py

On Monday, February 16, 2015, Oier notifications@github.com wrote:

> I am testing this too, but my idea is to set all the STRIPE variables in
> the same way.
> 
> unsing this:
> STRIPE_CURRENCY = os.environ.get("STRIPE_CURRENCY")
> 
> and set STRIPE_CURRENCY in the environment in some script outsite.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EuroPython/epcon/pull/13#issuecomment-74474682.

## 

Best,
Christian

**Comment by oiertwo** [comment]
True story. I will do it in your way :+1:

**Comment by raulcd** [comment]
:+1:

**Pull request merged**
