### PR TITLE
Serve the page over https locally.

### PR DESCRIPTION
**Pull request by umgelurgel**

### CODE REVIEW

**Comment by umgelurgel** [comment]
Closes #752

**Review by artcz — APPROVED** [review]
Thanks!

**Comment by matrixise** [comment]
I think we could use some files for the settings and avoiding to change the local configuration.

For example, `settings/{base|local|dev|production}.py

This settings file would be loaded in the manage.py or via the WSGI file and will use a module as python-dotenv or django-dotenv.

**Comment by umgelurgel** [comment]
@matrixise I agree - I would be happy to handle refactoring the settings, I've opened a ticket for it in https://github.com/EuroPython/epcon/issues/755, but from what I saw it was an issue that proved controversial before. I can refactor the settings as soon as I get an all clear on #755

**Pull request merged**
