### PR TITLE
new 500 error page - replacing Basque witchcraft with scottish castle.

### PR DESCRIPTION
**Pull request by artcz**
Also updated urls.py style to more modern django – removing patterns() – and added some debugging urls for 500/403/400 templates.

### CODE REVIEW

**Comment by artcz** [comment]
Replacing old


With 
new

**Comment by malemburg** [comment]
Nice, but we need to make sure that we can use that image. Did you get it from the folder I had sent you ? We need to add the photo reference to the page we have for this.

**Comment by artcz** [comment]
yes, it's one of those from low-res folder, that we didn't use in the carousel.

**Comment by malemburg** [comment]
Please add this photo reference to the box:

Photo source: https://www.flickr.com/photos/giuseppemilo/17101840068/

Thanks.

**Comment by artcz** [comment]
Like this? (with full url under href='')

**Comment by matrixise** [comment]
@malemburg if you are ok we could merge this PR.

**Comment by malemburg** [comment]
Thanks, Artur

**Pull request merged**
