### PR TITLE
Upgrade Django version

### PR DESCRIPTION
**Pull request by patrick91**
This PR updates Django to 1.8 and Django CMS to latest (3.4).

We decided to remote all the django cms contents (that were breaking the migrations) and recreate the pages from scratch. So in order to do that you need to delete a number of tables:

```
drop table djangocms_text_ckeditor_text;
drop table cms_aliaspluginmodel;                  
drop table cms_cmsplugin;                         
drop table cms_globalpagepermission;              
drop table filer_clipboard;
drop table cms_globalpagepermission_sites;        
drop table filer_clipboarditem;
drop table cms_page;                              
drop table filer_file;
drop table cms_page_placeholders;                 
drop table filer_folder;
drop table cms_pagepermission;                    
drop table filer_folderpermission;
drop table cms_pageuser;                          
drop table filer_image;
drop table cms_pageusergroup;                     
drop table cms_placeholder;                       
drop table cms_placeholderreference;              
drop table menus_cachekey;
drop table cms_staticplaceholder;                 
drop table cms_title;                             
drop table cms_usersettings;                      
drop table cms_utils_markituppluginmodel;         
drop table cmsplugin_filer_file_filerfile;        
drop table cmsplugin_filer_folder_filerfolder;    
drop table cmsplugin_filer_image_filerimage;      
drop table cmsplugin_filer_image_thumbnailoption; 
drop table cmsplugin_filer_link_filerlinkplugin;  
drop table cmsplugin_filer_teaser_filerteaser;    
drop table cmsplugin_filer_video_filervideo;      
drop table cmsplugin_grid;                        
drop table cmsplugin_gridcolumn;                  
drop table south_migrationhistory;
drop table django_content_type;
```
 
and fake the initial migrations:
note, I've deleted the django content type table since it was throwing errors.

```
python manage.py migrate contenttypes
python manage.py migrate auth 0001 --fake
python manage.py migrate contenttypes 0001 --fake
python manage.py migrate admin 0001 --fake
python manage.py migrate redirects 0001 --fake
python manage.py migrate sites 0001 --fake
python manage.py migrate sessions 0001 --fake
python manage.py migrate authority 0001 --fake
python manage.py migrate django_comments 0001 --fake
python manage.py migrate easy_thumbnails 0001 --fake
python manage.py migrate easy_thumbnails 0002 --fake
python manage.py migrate hcomments 0001 --fake
python manage.py migrate social_auth 0001 --fake
python manage.py migrate tagging 0001 --fake
python manage.py migrate taggit 0001 --fake
python manage.py migrate default 0001 --fake
```

and finally migrate everything

```
python manage.py migrate
```

### CODE REVIEW

**Comment by alexsavio** [comment]
@patrick91 How is the db migration?

**Comment by patrick91** [comment]
@alexsavio I'm having a lot of troubles with django cms migrations (mainly with its plugins).
I was thinking to make a manual migration. Happy to take suggestions tho :)

**Comment by alexsavio** [comment]
We have to keep only the important tables (users, speakers, talks, invoices, orders, tracks, conferences...). Can we throw away the tables that only have stuff for the CMS? It would be easier to regenerate that from the CMS directly, manually.

**Comment by malemburg** [comment]
For 2017 we will have to edit most CMS pages anyway, so recreating them from scratch would be a possibility, if the migration is too much of a hassle.

**Comment by patrick91** [comment]
@alexsavio @malemburg oh. That's good news! Will check everything again soon, hopefully during the weekend :)

**Comment by alexsavio** [comment]
Any news?

**Comment by patrick91** [comment]
Hey Alex, not really :( I've been ultra busy these weeks. I was wondering if we can have a dev.europython.eu site so we can start doing some tests. The website should work (at least mostly) with the updated requirements and dropping the cms tables (I mean skipping the migration and recreating them)

**Comment by alexsavio** [comment]
@malemburg @barrachri would it be possible to setup a dev site? I would like to learn how to do it as well, what is the configuration with the containers as well...

Is the process written somewhere? DockerFiles?

**Pull request merged**
