### PR TITLE
Remove the 'canceled' talks from the schedule

### PR DESCRIPTION
**Pull request by matrixise**
with this patch, I remove the 'canceled' talks from the schedule for the public part (logged or not).

```
/p3/schedule/<conference>/  p3.views.schedule.schedule  p3-schedule 
/p3/schedule/<conference>/list/ p3.views.schedule.schedule_list p3-schedule-list    
```

### CODE REVIEW

**Comment by malemburg** [comment]
Thanks for the PR, but I think it would be better to show the canceled as canceled in the schedule rather than just removing them. That way people will notice when looking at the schedule (e.g. in case they had planned to go).

The removal can then be done manually (by removing the talk from the schedule), in case the slot is reused for another talk.

**Comment by matrixise** [comment]
ok, in this case, my PR is useless and we need to change the template. any style for the canceled talk ?

**Comment by alexsavio** [comment]
it shouldn't show up.

On Fri, 8 Jul 2016, 18:42 Stéphane Wirtel, notifications@github.com wrote:

> ok, in this case, my PR is useless and we need to change the template. any
> style for the canceled talk ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/EuroPython/epcon/pull/376#issuecomment-231410043, or mute
> the thread
> https://github.com/notifications/unsubscribe/ACW4jGoBUqJuLEOKs9b-rL9tej0_YK1iks5qTn38gaJpZM4JEFlZ
> .
> 
> ## 

Sent from my phone, sorry for brevity or typos.

**Comment by europython-society** [comment]
On 08.07.2016 19:53, Alexandre M. S. wrote:

> it shouldn't show up.

I disagree. Please see my comment further up.

Canceled talks should be removed from the schedule manually.
Leaving it on the schedule is a valid use case, e.g. to
signal cancellations on short notice during the conference.

We used to do this by add "_Canceled_ - " to the title
in previous years.

## 

Marc-Andre Lemburg
eGenix.com

Professional Python Services directly from the Experts (#1, Jul 08 2016)

> > > Python Projects, Coaching and Consulting ...  http://www.egenix.com/
> > > Python Database Interfaces ...           http://products.egenix.com/
> > > Plone/Zope Database Interfaces ...           http://zope.egenix.com/
> > > 
> > > ---

::: We implement business ideas - efficiently in both time and costs :::

   eGenix.com Software, Skills and Services GmbH  Pastor-Loeh-Str.48
    D-40764 Langenfeld, Germany. CEO Dipl.-Math. Marc-Andre Lemburg
           Registered at Amtsgericht Duesseldorf: HRB 46611
               http://www.egenix.com/company/contact/
                      http://www.malemburg.com/

**Comment by barrachri** [comment]
I agree with Marc.
Probably we should have different status:
Proposed, Accepted, Canceled and maybe Removed

It would be nice to have a filter inside the admin, at least to make clear talks where speakers said "sorry, I can't".

**Comment by matrixise** [comment]
I do agree with a new status for the talks "Proposed", "Accepted", "Canceled", "Removed" (Removed, in fact, we could drop it, but I prefer to keep the talk in the database).

**Comment by alexsavio** [comment]
What's the point of 'Removed'? I think 'Canceled' would work wouldn't it?

**Comment by alanderex** [comment]
Indeed a 'removed' or maybe better 'invisible' status would be nice since sometime we do have submissions in the system we don't want to publicise, yet - like:
- keynotes
- drafts for sponsored sessions
- any other session we require for planning purposes but won't want to show in public.

**Comment by alexsavio** [comment]
Is this still up? @alanderex, then the way I see it is 'removed' (or I prefer, cancelled) is one status, and 'invisible' is another. I thought we could use 'accepted' as 'invisible', but I agree that it makes sense: an 'invisible' talk is an 'accepted' talk already scheduled.

**Comment by malemburg** [comment]
I don't think it's a good idea to have these discussions on a PR.

I've opened #589 and #590 to track the things discussed here and will close the PR.

**Comment by alanderex** [comment]
I think the public doesn’t see the non accepted talks,  only the soaker when looted in. So it’s fine to close it.

Von meinem iPhone gesendet

**Pull request closed without merging**
