### PR TITLE
[WIP] Add tests structure

### PR DESCRIPTION
**Pull request by marcoacierno**
Initial test structure for function tests using the technique BDD.

I used `pytest-bdd` instead of `behave` because we need fixtures support. 
Also, I use a git installed version of pytest-bdd because I need the `datatable` feature (when https://github.com/pytest-dev/pytest-bdd/pull/180 is merged we can use the normal dependency)

Right now there is only one test to check if everything is working correctly.

### CODE REVIEW

**Comment by matrixise** [comment]
Hi Marco,

This skeleton is really useful, do you think you have finished to work on it or will you add some new features ?

I am going to add the tests for the stripe part in the application and maybe we could use your skeleton.

**Comment by patrick91** [comment]
@marcoacierno is this good to merge?

**Comment by marcoacierno** [comment]
I need to check but the test part should be fine, we just need to merge the PR #417 otherwise the test settings file cannot be imported (I cannot remember the error now)

**Comment by patrick91** [comment]
Merged :)

**Comment by LuRsT** [comment]
If this is merged, can we close it?

**Comment by marcoacierno** [comment]
Hello,
sorry for the late response guys.

I did a git rebase so this code is updated with the PR (storage moved to helper function).

I need to test that everything is still working, but the PR itself should be ready. (I just need to reconfigure my environment to test sorry)

**Comment by alexsavio** [comment]
I don't understand what happened here. @patrick91, could you please check?

**Comment by marcoacierno** [comment]
I see there is already a test structure pushed in the repo so I don't see any reason to keep this PR open, also the repo code changed a lot since I did this PR so I am not sure everything still works

**Pull request closed without merging**
