### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by malemburg** [comment]
Could you rebase this against ep2021 ? Thanks.

**Comment by hugovk** [comment]
Done!

**Comment by hugovk** [comment]
@malemburg Happy new year! Is this PR still relevant or shall we close it?

**Comment by malemburg** [comment]
Looking at the code, it still is relevant, but I'm not sure whether ep2021 still is the right branch to patch against. Someone from the web WG will have to chime in (I'm no longer involved, sorry).

**Review by fpierfed — APPROVED** [review]

**Pull request merged**
