### PR TITLE
changed some field limits and removed duration field

### PR DESCRIPTION
**Pull request by barrachri**
Happy new year !

### CODE REVIEW

**Comment by malemburg** [comment]
Happy new year as well :-)

I think the approach you have taken to encode the duration into the talk type is not a good approach. It would be better to make this explicit by adding another global which maps talk type to a duration.

Apart from this, we will also need to run a script on the existing database to update all talk types to the new codes.

Overall, I'm not convinced that removing the duration is a good idea, since it removes a lot of flexibility in scheduling. Instead, I think we ought to make the submission types more flexible (as you did), and then use this to set the default duration. The program WG can then adapt the settings as necessary during planing.

BTW: While the title of the PR implies that the duration field is being removed, the patch itself only moves the duration field next to the type field, so in a way you are already doing what I think is the better strategy :-)

The other changes are fine.

**Comment by malemburg** [comment]
PS: The type changes will likely need some more work, since the code is full of implicit assumptions about the type chars (one of the reasons why I think it's better to make things explicit).

**Comment by barrachri** [comment]
Hi Marc,

1) I know that extract the duration of a talk from a string is not the best way....could be this solution better ? http://paste.ofcode.org/sp5Jx7AZak8xjL6qxvWYCV 

 2) Probably we should check something, but in general from what I see it works in the same way as before (https://dev.europython.eu/p3/schedule/ep2015/). Maybe we just need update the old proposal types to the new one.

3) I don't know why they prefer to remove the duration field from the form. Probably they want the type of the talk and the duration linked in an hard way.

4) the duration field has been removed from the template...

**Comment by malemburg** [comment]
The ofcode.org server seems to be down at the moment, so I can't comment. I'd simply set up a separate constant dict to map the type to a (default) duration.

Removing the duration field from the CfP form is fine. I guess I simply misunderstood your PR title.

Regarding the types on existing records from 2015, we could handle this in a couple of ways:
1. Remove all 2015 entries from the database - then we'd lose possible opportunities for future gamification or analysis based on the old data.
2. Convert old entries to the new format using a script.
3. Keep the old entries and only hide them from the CfP input form.

Option 2 would be the cleanest approach. Option 3 would likely work as well and we could always implement option 2 at some later point.

**Comment by malemburg** [comment]
I tried the ofcode.org link again today, but it seems the snippet has expired. Could you upload it as gist ?

**Comment by barrachri** [comment]
https://gist.github.com/barrachri/9045e79a0fb562601ff2#file-duration-py

**Comment by malemburg** [comment]
@barrachri perfect.

**Comment by malemburg** [comment]
Could you fix the PR to include the respective change or close this one and create a new one ?

**Comment by barrachri** [comment]
Hi @malemburg, done.

**Comment by malemburg** [comment]
Thanks, then let's see how this works out...

**Pull request merged**
