### PR TITLE
Add meta tags for twitter and facebook

### LINKED ISSUE #914: Twittercards are missing
We used to have twittercards, .ie

`
    
    
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@europython" />
    <meta name="twitter:title" content="10 years of EuroPython and the Python community" />
    <meta name="twitter:description" content="This talk will take you on a journey from Birmingham to Edinburgh via Florence, Berlin, Bilbao and Rimini. The last 10 years of EuroPytho..." />
    <meta name="twitter:image" content="https://ep2018.europython.eu/static/p6/images/favicon-256x256.png" />

`

AFAIR for the most page we used something generic, for the talks we used the short  description as description

### PR DESCRIPTION
**Pull request by patrick91**
Closes #914

TODO:

- [x] image generation for blog posts

### CODE REVIEW

**Comment by patrick91** [comment]
To create the social cards we can use https://weasyprint.org/

Template:

Facebook Post-1
Facebook Post

**Review by artcz — APPROVED** [review]
Lgtm :)

**Comment by patrick91** [comment]
@artcz can you have a look at this commit? https://github.com/EuroPython/epcon/pull/930/commits/49df118084f3cd85dbe85d661ce222931fc88580

I think we need to update the seed data that we have, the talk I'm using for test doesn't have a name for the speaker

**Comment by artcz** [comment]
@patrick91 looks ok; as a small nitpick I'd probably put a view in a separate module, like 'conference/social_cards.py`; for the name of the speaker – it should be the same what AssopyUser.name() returns.

**Review by artcz — APPROVED** [review]
LGTM

**Pull request merged**
