### PR TITLE
Remove/unused things part 1

### PR DESCRIPTION
**Pull request by artcz**
This is part 1 of series of PRs where we remove a lot of unused things. Starting with documents/ (that contains old ep mockups), and locales (we're english only these days)

### CODE REVIEW

**Comment by artcz** [comment]
Because Github is not ideal when it comes to diffs that touch a lot of files here's the current diffstat:

```
git --no-pager diff --stat dev/ep2019                                                         (git)-[remove/unused-things-part-1] 
 bin/pre-commit                                              |    3 -
 deps/PyQRNative.py                                          |  980 ------------------------------------------------------
 documents/badge/ep2011/Arial_Unicode.ttf                    |  Bin 23278008 -> 0 bytes
 documents/badge/ep2011/League_Gothic.ttf                    |  Bin 42992 -> 0 bytes
 documents/badge/ep2011/day1.png                             |  Bin 512188 -> 0 bytes
 documents/badge/ep2011/day2.png                             |  Bin 511097 -> 0 bytes
 documents/badge/ep2011/day3.png                             |  Bin 511889 -> 0 bytes
 documents/badge/ep2011/day4.png                             |  Bin 512476 -> 0 bytes
 documents/badge/ep2011/day5.png                             |  Bin 511812 -> 0 bytes
 documents/badge/ep2011/jokes/allyourbase.png                |  Bin 92740 -> 0 bytes
 documents/badge/ep2011/jokes/apple.png                      |  Bin 41090 -> 0 bytes
 documents/badge/ep2011/jokes/bertos.png                     |  Bin 4460 -> 0 bytes
 documents/badge/ep2011/jokes/bofh.png                       |  Bin 4768 -> 0 bytes
 documents/badge/ep2011/jokes/bycicle.png                    |  Bin 107617 -> 0 bytes
 documents/badge/ep2011/jokes/cake.png                       |  Bin 6484 -> 0 bytes
 documents/badge/ep2011/jokes/camcorder.png                  |  Bin 2321 -> 0 bytes
 documents/badge/ep2011/jokes/campi.png                      |  Bin 1010 -> 0 bytes
 documents/badge/ep2011/jokes/challenge.png                  |  Bin 1547 -> 0 bytes
 documents/badge/ep2011/jokes/ciuccio.png                    |  Bin 1542 -> 0 bytes
 documents/badge/ep2011/jokes/disqus.png                     |  Bin 22684 -> 0 bytes
 documents/badge/ep2011/jokes/dontpanic.png                  |  Bin 275296 -> 0 bytes
 documents/badge/ep2011/jokes/enthought.png                  |  Bin 3598 -> 0 bytes
 documents/badge/ep2011/jokes/f-secure.png                   |  Bin 2182 -> 0 bytes
 documents/badge/ep2011/jokes/fedora.png                     |  Bin 40386 -> 0 bytes
 documents/badge/ep2011/jokes/female.png                     |  Bin 3648 -> 0 bytes
 documents/badge/ep2011/jokes/fluidinfo.png                  |  Bin 1763 -> 0 bytes
 documents/badge/ep2011/jokes/giullare.png                   |  Bin 7497 -> 0 bytes
 documents/badge/ep2011/jokes/iphone.png                     |  Bin 47856 -> 0 bytes
 documents/badge/ep2011/jokes/lundh.png                      |  Bin 66684 -> 0 bytes
 documents/badge/ep2011/jokes/male.png                       |  Bin 4435 -> 0 bytes
 documents/badge/ep2011/jokes/maya.png                       |  Bin 28931 -> 0 bytes
 documents/badge/ep2011/jokes/merengue.png                   |  Bin 4882 -> 0 bytes
 documents/badge/ep2011/jokes/moinmoin.png                   |  Bin 9663 -> 0 bytes
 documents/badge/ep2011/jokes/openquake.png                  |  Bin 4894 -> 0 bytes
 documents/badge/ep2011/jokes/openstack.png                  |  Bin 30580 -> 0 bytes
 documents/badge/ep2011/jokes/panino.png                     |  Bin 1452 -> 0 bytes
 documents/badge/ep2011/jokes/perl.png                       |  Bin 4121 -> 0 bytes
 documents/badge/ep2011/jokes/plaster.png                    |  Bin 685 -> 0 bytes
 documents/badge/ep2011/jokes/postgres.png                   |  Bin 16905 -> 0 bytes
 documents/badge/ep2011/jokes/pycharm.png                    |  Bin 87665 -> 0 bytes
 documents/badge/ep2011/jokes/pyhp.png                       |  Bin 33252 -> 0 bytes
 documents/badge/ep2011/jokes/pypy.png                       |  Bin 9835 -> 0 bytes
 documents/badge/ep2011/jokes/pyside.png                     |  Bin 2324 -> 0 bytes
 documents/badge/ep2011/jokes/rapple.png                     |  Bin 12278 -> 0 bytes
 documents/badge/ep2011/jokes/riverbank.png                  |  Bin 4232 -> 0 bytes
 documents/badge/ep2011/jokes/royale.png                     |  Bin 504333 -> 0 bytes
 documents/badge/ep2011/jokes/skeleton.png                   |  Bin 829 -> 0 bytes
 documents/badge/ep2011/jokes/sourceforge.png                |  Bin 6899 -> 0 bytes
 documents/badge/ep2011/jokes/spiderman.png                  |  Bin 40408 -> 0 bytes
 documents/badge/ep2011/jokes/spotify.png                    |  Bin 7239 -> 0 bytes
 documents/badge/ep2011/jokes/stackless.png                  |  Bin 7402 -> 0 bytes
 documents/badge/ep2011/jokes/taz.png                        |  Bin 18614 -> 0 bytes
 documents/badge/ep2011/jokes/ubuntu.png                     |  Bin 32784 -> 0 bytes
 documents/badge/ep2011/jokes/wizard.png                     |  Bin 17037 -> 0 bytes
 documents/badge/ep2011/lite.png                             |  Bin 511006 -> 0 bytes
 documents/badge/ep2011/logo.png                             |  Bin 3002 -> 0 bytes
 documents/badge/ep2011/staff.png                            |  Bin 523422 -> 0 bytes
 documents/badge/ep2011/standard.png                         |  Bin 510055 -> 0 bytes
 documents/badge/ep2012/Arial_Unicode.ttf                    |  Bin 23278008 -> 0 bytes
 documents/badge/ep2012/Badge Demo.png                       |  Bin 54147 -> 0 bytes
 documents/badge/ep2012/conf.py                              |  128 -------
 documents/badge/ep2012/day1.png                             |  Bin 471668 -> 0 bytes
 documents/badge/ep2012/day2.png                             |  Bin 471614 -> 0 bytes
 documents/badge/ep2012/day3.png                             |  Bin 498575 -> 0 bytes
 documents/badge/ep2012/day4.png                             |  Bin 499068 -> 0 bytes
 documents/badge/ep2012/day5.png                             |  Bin 499435 -> 0 bytes
 documents/badge/ep2012/lite.png                             |  Bin 465067 -> 0 bytes
 documents/badge/ep2012/logo.png                             |  Bin 3002 -> 0 bytes
 documents/badge/ep2012/staff.png                            |  Bin 513248 -> 0 bytes
 documents/badge/ep2012/standard.png                         |  Bin 464032 -> 0 bytes
 documents/badge/ep2013/Arial_Unicode.ttf                    |  Bin 23278008 -> 0 bytes
 documents/badge/ep2013/Badge Demo.jpg                       |  Bin 1129914 -> 0 bytes
 documents/badge/ep2013/League_Gothic.otf                    |  Bin 24472 -> 0 bytes
 documents/badge/ep2013/conf.py                              |  133 --------
 documents/badge/ep2013/day1.png                             |  Bin 174076 -> 0 bytes
 documents/badge/ep2013/day2.png                             |  Bin 176142 -> 0 bytes
 documents/badge/ep2013/day3.png                             |  Bin 176938 -> 0 bytes
 documents/badge/ep2013/day4.png                             |  Bin 174815 -> 0 bytes
 documents/badge/ep2013/day5.png                             |  Bin 175351 -> 0 bytes
 documents/badge/ep2013/lite.png                             |  Bin 180931 -> 0 bytes
 documents/badge/ep2013/logo-blu.png                         |  Bin 16526 -> 0 bytes
 documents/badge/ep2013/logo-panna.png                       |  Bin 16526 -> 0 bytes
 documents/badge/ep2013/logo.png                             |  Bin 3002 -> 0 bytes
 documents/badge/ep2013/staff.png                            |  Bin 465849 -> 0 bytes
 documents/badge/ep2013/standard.png                         |  Bin 172151 -> 0 bytes
 documents/badge/pycon5/Ubuntu-Title.ttf                     |  Bin 15108 -> 0 bytes
 documents/badge/pycon5/staff.png                            |  Bin 42390 -> 0 bytes
 documents/badge/pycon5/standard.png                         |  Bin 38619 -> 0 bytes
 documents/badge/pycon5/star.png                             |  Bin 3454 -> 0 bytes
 documents/cover/ep2012/Arial_Unicode.ttf                    |  Bin 23278008 -> 0 bytes
 documents/cover/ep2012/League Gothic.otf                    |  Bin 17332 -> 0 bytes
 documents/cover/ep2012/cover-start-end.png                  |  Bin 519895 -> 0 bytes
 documents/cover/ep2013/Arial_Unicode.ttf                    |  Bin 23278008 -> 0 bytes
 documents/cover/ep2013/League Gothic.otf                    |  Bin 17332 -> 0 bytes
 documents/cover/ep2013/League_Gothic.otf                    |  Bin 24472 -> 0 bytes
 documents/cover/ep2013/cover-start-end.png                  |  Bin 1662490 -> 0 bytes
 documents/europython-mockups/.DS_Store                      |  Bin 12292 -> 0 bytes
 documents/europython-mockups/blog-index.html                |  333 -------------------
 documents/europython-mockups/blog-post.html                 |  506 ----------------------------
 documents/europython-mockups/index.html                     |  376 ---------------------
 documents/europython-mockups/intern.html                    |  385 ----------------------
 documents/europython-mockups/speaker-detail.html            |  306 -----------------
 documents/europython-mockups/static/.DS_Store               |  Bin 12292 -> 0 bytes
 documents/europython-mockups/static/f/League_Gothic.eot     |  Bin 43942 -> 0 bytes
 documents/europython-mockups/static/f/League_Gothic.otf     |  Bin 17332 -> 0 bytes
 documents/europython-mockups/static/f/League_Gothic.svg     |  296 -----------------
 documents/europython-mockups/static/f/League_Gothic.woff    |  Bin 13556 -> 0 bytes
 documents/europython-mockups/static/i/.DS_Store             |  Bin 15364 -> 0 bytes
 documents/europython-mockups/static/i/arrow-right.png       |  Bin 1041 -> 0 bytes
 documents/europython-mockups/static/i/badge-b.png           |  Bin 1366 -> 0 bytes
 documents/europython-mockups/static/i/badge-n.png           |  Bin 1261 -> 0 bytes
 documents/europython-mockups/static/i/body.png              |  Bin 2945 -> 0 bytes
 documents/europython-mockups/static/i/border.png            |  Bin 518 -> 0 bytes
 documents/europython-mockups/static/i/bullet-aside.png      |  Bin 331 -> 0 bytes
 documents/europython-mockups/static/i/bullet.png            |  Bin 334 -> 0 bytes
 documents/europython-mockups/static/i/button-b.png          |  Bin 587 -> 0 bytes
 documents/europython-mockups/static/i/button-n.png          |  Bin 606 -> 0 bytes
 documents/europython-mockups/static/i/comment-reply.png     |  Bin 372 -> 0 bytes
 documents/europython-mockups/static/i/delicious-16x16.png   |  Bin 1569 -> 0 bytes
 documents/europython-mockups/static/i/digg-this-16x16.png   |  Bin 1564 -> 0 bytes
 documents/europython-mockups/static/i/dopplr-16x16.png      |  Bin 1998 -> 0 bytes
 documents/europython-mockups/static/i/europython-logo.png   |  Bin 29445 -> 0 bytes
 documents/europython-mockups/static/i/facebook-16x16.png    |  Bin 1576 -> 0 bytes
 documents/europython-mockups/static/i/favicon.ico           |  Bin 1150 -> 0 bytes
 documents/europython-mockups/static/i/favicon.png           |  Bin 440 -> 0 bytes
 documents/europython-mockups/static/i/footer.jpg            |  Bin 13461 -> 0 bytes
 documents/europython-mockups/static/i/friendfeed-16x16.png  |  Bin 445 -> 0 bytes
 documents/europython-mockups/static/i/headshot-ph.jpg       |  Bin 5570 -> 0 bytes
 documents/europython-mockups/static/i/home-where.jpg        |  Bin 34117 -> 0 bytes
 documents/europython-mockups/static/i/hr.png                |  Bin 3904 -> 0 bytes
 documents/europython-mockups/static/i/icon-amex.png         |  Bin 1678 -> 0 bytes
 documents/europython-mockups/static/i/icon-bird.png         |  Bin 516 -> 0 bytes
 documents/europython-mockups/static/i/icon-clock.png        |  Bin 770 -> 0 bytes
 documents/europython-mockups/static/i/icon-feed.png         |  Bin 565 -> 0 bytes
 documents/europython-mockups/static/i/icon-mastercard.png   |  Bin 1176 -> 0 bytes
 documents/europython-mockups/static/i/icon-paypal.png       |  Bin 1006 -> 0 bytes
 documents/europython-mockups/static/i/icon-post.png         |  Bin 278 -> 0 bytes
 documents/europython-mockups/static/i/icon-speakers.png     |  Bin 2364 -> 0 bytes
 documents/europython-mockups/static/i/icon-visa.png         |  Bin 1204 -> 0 bytes
 documents/europython-mockups/static/i/iphone.png            |  Bin 63144 -> 0 bytes
 documents/europython-mockups/static/i/linkedin-16x16.png    |  Bin 1568 -> 0 bytes
 documents/europython-mockups/static/i/marker_hotel.png      |  Bin 858 -> 0 bytes
 documents/europython-mockups/static/i/marker_hotel_conv.png |  Bin 2893 -> 0 bytes
 documents/europython-mockups/static/i/marker_pycon.png      |  Bin 2893 -> 0 bytes
 documents/europython-mockups/static/i/newsvine-16x16.png    |  Bin 1642 -> 0 bytes
 documents/europython-mockups/static/i/reddit-16x16.png      |  Bin 1881 -> 0 bytes
 documents/europython-mockups/static/i/sample-figure.jpg     |  Bin 22916 -> 0 bytes
 documents/europython-mockups/static/i/sample-floated.jpg    |  Bin 1991 -> 0 bytes
 documents/europython-mockups/static/i/speakers-ph.png       |  Bin 75327 -> 0 bytes
 documents/europython-mockups/static/i/speakers-wanted.png   |  Bin 29953 -> 0 bytes
 documents/europython-mockups/static/i/speakers.jpg          |  Bin 30066 -> 0 bytes
 documents/europython-mockups/static/i/sponsor-ph.png        |  Bin 2270 -> 0 bytes
 documents/europython-mockups/static/i/sponsor.png           |  Bin 4799 -> 0 bytes
 documents/europython-mockups/static/i/stumbleupon-16x16.png |  Bin 1730 -> 0 bytes
 documents/europython-mockups/static/i/twitter-16x16.png     |  Bin 1636 -> 0 bytes
 documents/europython-mockups/static/j/.DS_Store             |  Bin 6148 -> 0 bytes
 documents/europython-mockups/static/j/html5.js              |    5 -
 documents/europython-mockups/static/s/.DS_Store             |  Bin 6148 -> 0 bytes
 documents/europython-mockups/static/s/base.css              | 1138 ---------------------------------------------------------------
 documents/europython-mockups/static/s/blog.css              |  306 -----------------
 documents/europython-mockups/static/s/cms.css               |  280 ----------------
 documents/europython-mockups/static/s/form.css              |  175 ----------
 documents/europython-mockups/static/s/grid-14.css           |  163 ---------
 documents/europython-mockups/static/s/grid.css              |  185 -----------
 documents/europython-mockups/static/s/ie.css                |    1 -
 documents/europython-mockups/static/s/mobile.css            |    7 -
 documents/europython-mockups/static/s/reset.css             |   58 ----
 documents/europython-mockups/static/s/schedule.css          |  225 -------------
 documents/europython-mockups/talk-detail.html               |  310 -----------------
 locale/en/LC_MESSAGES/django.po                             | 1854 ------------------------------------------------------------------------------------------------------
 locale/es/LC_MESSAGES/django.po                             | 1773 -------------------------------------------------------------------------------------------------
 locale/it/LC_MESSAGES/django.po                             | 1995 --------------------------------------------------------------------------------------------------------------
 172 files changed, 11921 deletions(-)
```

**Comment by alexsavio** [comment]
The translations, aren't they worth anything? :(
The rest...feels good to leave.
We could also make a blob cleanup of the repository: http://alexsavio.github.io/git-cleanup-bfg.html

**Comment by artcz** [comment]
Translations are still in the repository, you'll just have to get them from previous commits. Nothing in git is really deleted unless you rewrite the history. :)

**Comment by alexsavio** [comment]
if you see it that way, then 👍

**Review by alexsavio — APPROVED** [review]

**Pull request merged**
