### PR TITLE
wip: add schedule api access point

### PR DESCRIPTION
**Pull request by alexsavio**
This is a proposal for a "API" access point where people can access the data of the accepted talks.

Please have a look and let me know what you think.

I still have to test it, but any push/help is appreciated.

### CODE REVIEW

**Comment by malemburg** [comment]
Please protect the API view using a special auth group, e.g. "API Access".

Please move the view module into the p3/views/. We should not have views outside this directory.

Please also convert the relative imports to absolute ones. Relative imports are a pain to maintain and there's no real need for them in applications (only in libraries which are meant to be integrated into apps, but even there you hardly need them).

Thanks.

**Comment by alexsavio** [comment]
Thanks Marc. I will do that. Regarding the access permissions, I thought that if everybody has access to the schedule page, why restrict access to the this?

**Comment by malemburg** [comment]
Because you have personal information in the API feed and also because people will forget that there are no permissions checks and going forward might add more details without being aware of a potential problem 
:-)

**Comment by alexsavio** [comment]
I added login_required to the view, but not sure how to create the "API group".

**Comment by malemburg** [comment]
I have created a group "API Access" for this.

You can follow this approach to test for it:

https://bradmontgomery.net/blog/restricting-access-by-group-in-django/

**Comment by malemburg** [comment]
I have merged this into ep2017 now. Should probably be forward merged into ep2018 as well. Can you take care of this ?

**Pull request merged**
