### PR TITLE
Allow to specify a talk domain

### PR DESCRIPTION
**Pull request by patrick91**
How it looks: 

screen shot 2018-04-08 at 19 04 42

@alanderex I've named it `Domain / Track`, not sure if is the correct working, also can I have a feedback on the help text?

> Select the domain of the talk, this will help us with the conference scheduling

@malemburg shall we rename the field to something else? I've reused the sub communities one :)

### CODE REVIEW

**Comment by malemburg** [comment]
I'm not sure whether this is a good approach, since we've used the sub communities field in the past and the database still references this under the old meaning.

It's probably better to add a new field ".topic" for this and also use this name in the form.

**Comment by patrick91** [comment]
@malemburg right, I'll hide that field and add another one. I'll actually close this pr and make another with this change and another one Alexander requested :)

**Comment by alanderex** [comment]
The subcommunites only carried PyData or none, it was not useful/used in the past (even PyData submitters left it blank)
@patrick91 Wording is fine.
Just to make sure: do we also have two fields for the level now? @patrick91
- Python programming level (currently Audience level)
- Domain level

**Comment by malemburg** [comment]
It's still better to have a new field and not reuse an existing one with a different meaning. We may well start using the sub community field again in the future for satellite events (and then hard code it into the submission form rather than ask people to select it).

**Pull request closed without merging**
