### PR TITLE
Remove ical generation from the website.

### PR DESCRIPTION
**Pull request by umgelurgel**
We've stopped using it last year - since we're using attendify.

### CODE REVIEW

**Comment by matrixise** [comment]
And if we move from attendify?

**Comment by umgelurgel** [comment]
> And if we move from attendify?

There's no plans to stop using attendify in the foreseeable future that I'm aware of, so it shouldn't be a concern.

**Review by aramboi — APPROVED** [review]
Looks good. :shipit: 

 If we have demand for this we should definitely look into using a dedicated library instead of rolling our own solution.

**Comment by umgelurgel** [comment]
Yeah, that's one of the main reasons for removing it - using a tested solution for this will leave us with a lot less code to maintain :)

**Pull request merged**
