### PR TITLE
Improve talk schedule information retrieval

### PR DESCRIPTION
**Pull request by alexsavio**

### CODE REVIEW

**Comment by malemburg** [comment]
Hi Alex, could you please update the PR or create a new one for this ? Thanks.

**Comment by alexsavio** [comment]
Sure, I will.

**Comment by alexsavio** [comment]
I don't remember anymore what I was doing here.

**Comment by alexsavio** [comment]
Should we close this?

**Comment by malemburg** [comment]
Yes, let's close. It's not obvious to me from looking at the patch either :-)

**Pull request closed without merging**
