### PR TITLE
[WIP] Add stripe_charge_id in the Order model

### PR DESCRIPTION
**Pull request by matrixise**
[WIP] Add a test for the stripe_charge_id
[WIP] Add new requirements for the tests

just execute python manage.py test

### CODE REVIEW

**Comment by alexsavio** [comment]
Everything seems correct. If it works I am +1 for it. django-payments could be a good solution as well, but would take time and it's another dependency to watch for.

**Comment by malemburg** [comment]
Thanks, Stéphane. Could you please add migrations to the PR as well ?

**Comment by matrixise** [comment]
@malemburg of course, just used Django in Test and Debug mode and not added the migrations. sorry :/

**Comment by matrixise** [comment]
```
# make a backup before
python manage.py migrate --fake-initial
python manage.py migrate
```

**Comment by matrixise** [comment]
@alexsavio and @malemburg please, could you review ?

**Comment by alexsavio** [comment]
should we have a dev-requirements.txt file for the dependencies for testing?

**Comment by europython-society** [comment]
On 13.02.2017 14:26, Alexandre M. S. wrote:
> should we have a dev-requirements.txt file for the dependencies for testing?

Yes, but please call it requirements-dev.txt, that's more standard.

-- 
Marc-Andre Lemburg
eGenix.com

**Comment by matrixise** [comment]
@europython-society done

**Comment by malemburg** [comment]
Thanks for the PR.

**Pull request merged**
