### PR TITLE
Add feedback bar styles

### LINKED ISSUE #636: Add missing CSS to the notifications/messages.
Currently the notifications/(django messages) are not properly styled; attached screenshot of notification after cfp submission.

invisible-notification-after-cfp-submission

### PR DESCRIPTION
**Pull request by patrick91**
Makes message more prominent.

@artcz shall I add some javascript to hide the message(s)?

Closes #636

### CODE REVIEW

**Comment by artcz** [comment]
Do we still have different colors for warning/error/info?

**Comment by artcz** [comment]
Re: javascript – could be, but we probably don't need it, since it will disappear on first refresh.

**Comment by matrixise** [comment]
@artcz any status about this PR ?

**Comment by artcz** [comment]
I'll merge this, so it's no longer outstanding, we can add colors later, if we even need them.

**Pull request merged**
